server:
  port: 8081
spring:
  application:
    name: myDemo-admin
  # 关键修正：将druid和dynamic配置置于datasource下
  datasource:
    # 以下是Druid连接池的通用参数
    druid:
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
      validation-query: SELECT 1
    # 以下是动态数据源（多数据源）配置
    dynamic:
      primary: user
      # 未匹配到数据源时，true抛异常，false使用默认数据源
      strict: false
      datasource:
        user:
          url: jdbc:mysql://192.168.206.247:3306/myDemo_User?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: lihenian
          password: asdASD10086.
        goods:
          url: jdbc:mysql://192.168.206.247:3306/myDemo_goods?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: lihenian
          password: asdASD10086.

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.206.247:8848
        namespace: public
        group: DEFAULT_GROUP
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: myDemo-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/ssoLogin
      - /admin/register
      - /upload/product/**


